<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>junkTrade</title>
    
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link rel ="stylesheet" href ="css/bootstrap-theme.css" >


    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" rel="stylesheet">
    <link href ="css/main.css" rel ="stylesheet">

    <!-- google font  -->
    <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet"> 
    <style>
      .jumbotron {
          background-image: url(img/jombopic.jpg);
      }
      .jid{
        background-color: orange;
        text-align:center;
        margin-bottom:0;
        padding-bottom: 3%;
      }

    </style>
    
    <script src="bower_components/angular/angular.min.js"></script>
    <script src="bower_components/angular-route/angular-route.min.js"></script>
    <script src ="js/jquery-3.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <!-- <script src="js/main.js"></script> -->

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img alt ="logo" width ="30px" height ="30px" src ="img/logo.png"></a>
          <a class ="navbar-brand" href ="index.phtml">junkTrade</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Electronics</a></li>
            <li><a href="#">Furniture</a></li>
            <li><a href="#">Books & Magazines</a></li>
            <li><a href="#">Clothes</a></li>
          </ul>
        </li>
      </ul>
          <form class="navbar-form navbar-left" role="form">
            <div class="form-group">
              <input type="text" placeholder="search for junk" class="form-control">
            </div>
            <!--change to icon-->
            <button type="submit" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
            <!--this is not rendering the login page as it shoul -->
            <ul class = "nav navbar-nav navbar-right ">
                <li><a href ="templates/login.php">Login</a></li>
            </ul>
            <ul class = "nav navbar-nav navbar-right ">
                <li><a href ="templates/registration.phtml">Sign up</a></li>
            </ul>
           <!--<ul class="nav navbar-nav navbar-right ">
                <li><button type="button" class="btn btn-primary btn-lg" onclick="window.location='templates/login.html'">login</button></li>
            </ul> -->
         
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 style="color:#096790 ;text-shadow: 4px 4px orange;font-family: 'Bowlby One SC', cursive;">Trade Your Junk Now!</h1>
        <h2 style="color:orange ;text-shadow: 4px 4px #096790;font-family: 'Bowlby One SC', cursive;"> Your junk can become someone's Treasure </h2></br>
            <a href ="templates/registration.phtml"><p><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
            Start Trading Now
            </button></p></a>


        <!--<a class="btn btn-primary btn-lg" href="#" role="button">start trading now &raquo;</a></p>-->
      </div>
    </div>
    <div class="container-fluid">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Its Simple and easy</h2>
          <p>Trading on JunkTrade could not be more Easy. Simply Register, Login, Upload and ...voilà!! you can start Trading items with other Users. It sure is easy, peasy. Your Gradmad can trade, your Aunty can Trade and even your pet Dog. </p>

          <p><img src ="img/easy.png" alt ="easy image" style ="width:30%; height: 30%;"></p>
        </div>
        <div class="col-md-4">
          <h2>No Money? No problem!</h2>
          <p>At JunkTrade we never make money an Issue. As a matter of fact the entire design of the application is based on the concept of "No Money". This makes it easy for students or individuals interested in "saving a Buck" to gain almost any item needed. Isn't that awesome?!?! </p>
          <p><img src ="img/nomoney.png" alt ="no money" style ="width:30%; height: 30%;"></p>
       </div>
        <div class="col-md-4">
          <h2>Find Trading Buddies</h2>
          <p>At JunkTrade Our goal is to form a strong community were people can not only share their "junk" but share freindship. We encourage you to find buddies who may have all the junk you need.It truely makes your trading experience a great one!</p>
           <p><img src ="img/buddy.png" alt ="buddy up" style ="width:30%; height: 30%;"></p>
        </div>
      </div>

      <div class ="row jid">
      	<div class ="col-md-12">
      		<h2>Welcome Home Junkies</h2>
      		<p>JunkTrade is a site dedicated to bringing you opportunities to acquire all the items you may need without the need for any monetary transactions. Simply sign up, upload an image and start trading. Its free and Easy.</p>
          <p>The application was built by 5 UWI students who had a desire to facilitate the trading of items among the UWI community without the need for money.As a result JunkTrade was built and has now expanded to serve not only UWI studnts but the whole of Trinidad. Anyone within Trinidad now has the opportunity to to sign up and start trading with others who live here. Developers at Junk Trade are currenly working towards making this application Internationally Available. Thanks for Stopping by, and dont forget to sign up and start trading.</p>
          <a href ="templates/registration.phtml"><button type="button" class="btn btn-primary btn-lg">
            Sign up for JunkTrade
            </button></a>
  
      </div>

      </div>
 


  <!--footer -->
  <div class="footer">
    <p> &copy; JunkTrade 2016 </p>
  </div>
    </div> <!-- /container -->        
</body>


</html>