<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>JunkTrade</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <!-- Latest compiled and minified CSS Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Main CSS -->
    <link href ="css/main.css" rel ="stylesheet">
    <link href="css/half-slider.css" rel="stylesheet">

    
    <!-- Scripts-->
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
    <style>
body {
  
  font-family: "Roboto Condensed", sans-serif;
}
}
</style>
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" style="padding-top: 0; margin:0;"><img alt ="logo" width ="70px" height ="500px" src ="img/logo.png" class="img-responsive" style="max-height:146%;"></a>
          <a class ="navbar-brand" href ="#">JunkTrade</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
      
            <!--this is not rendering the login page as it shoul -->
            <ul class = "nav navbar-nav navbar-right ">
              <li><a href ="templates/registration.phtml"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
              <li><a href ="templates/login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                
            </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Half Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('img/slide1.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Get all that you ever dreamed of</h1>
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('img/slide2.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Help others while helping yourself</h1>
                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('img/jombopic.jpg');"></div>
                <div class="carousel-caption">
                    <h2>A complete platform dedicated to trading</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>

    <!-- Page Content -->
     <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container ">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4 firstRow">
          <p><img class="img-circle" src="img/circle1.jpg" alt="Generic placeholder image" width="140" height="140"></p>
          <h2>Trade some books</h2>
         <p> Do you have books that you no longer need? Don't worry, you're in the right place. Trade them for something you need. You deserve it.</p>
          <p><a class="btn btn-default" href="templates/registration.phtml" role="button">sign me up now &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4 firstRow">
          <p><img class="img-circle" src="img/circle2.jpg" alt="Generic placeholder image" width="140" height="140"></p>
          <h2>Trade a bag </h2>
         <p>Are you looking for a bag to match your new shoes? Maybe you spent all your money on the shoes and can't afford a new bag. Despair no more, we got you covered!</p>
          <p><a class="btn btn-default" href="templates/registration.phtml" role="button">start trading  &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4 firstRow">
          <p><img class="img-circle" src="img/circle3.png" alt="Generic placeholder image" width="140" height="140"></p>
          <h2>Trade anything</h2>
         <p>If you can hold it, you can trade it for something better and more useful to you.Don't wait, join this exciting world of trade. Find that thing you always wanted.</p>
          <p><a class="btn btn-default" href="templates/registration.phtml" role="button">im excited &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        
      </div><!-- /.row -->


    <!-- end of first row -->
      <div style="background-color: lightblue;" class ="theRows row">
         <div class="col-md-8">
          <h1 style="color: #00BFFF;">Its Simple and easy</h1>
          <p>Trading on JunkTrade could not be more Easy. Simply Register, Login, Upload and ...voilà!! you can start Trading items with other Users. It sure is easy, peasy. Your Gradmad can trade, your Aunty can Trade and even your pet Dog. </p>
        </div>
        <div class="col-md-4">
          <p><img src ="img/easy.png" alt ="easy image" style ="width:70%; height: 70%;"></p>
        </div>
      </div> 


      <!--                    -->
      <div style="background-color: #E2A7BF;" class="row theRows">
       <div class="col-md-4">
        <p><img src ="img/nomoney.png" alt ="no money" style ="width:50%; height: 50%;"></p>
          </div>  
        <div class="col-md-8">
          <h1 style="color: #FF6347;">No Money? No problem!</h1>
          <p>At JunkTrade we never make money an Issue. As a matter of fact the entire design of the application is based on the concept of "No Money". This makes it easy for students or individuals interested in "saving a Buck" to gain almost any item needed. Isn't that awesome?!?! </p>
          </div>
         
        </div>

        <div style ="background-color: #BCA7E2;" class="row theRows">
      
        <div class="col-md-8">
          <h1 style="color:#663399;">Find Trading Buddies</h1>
          <p>At JunkTrade Our goal is to form a strong community were people can not only share their "junk" but share freindship. We encourage you to find buddies who may have all the junk you need.It truely makes your trading experience a great one!</p>
          </div>
            <div class="col-md-4">
           <p><img src ="img/buddy.png" alt ="buddy up" style ="width:70%; height: 70%;"></p>
        </div>
        </div> 


    </div>
    <!-- /.container -->

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>
