<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>Sign Up</title>
    
    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.css" rel="stylesheet">
    <link rel ="stylesheet" href ="../css/bootstrap-theme.css" >


    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" rel="stylesheet">
    <link href ="../css/main.css" rel ="stylesheet">
    <link href ="../css/form.css" rel ="stylesheet">

    <!-- google font  -->
    <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">

    <!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script> -->
    <script src="../bower_components/angular/angular.min.js"></script>
    <script src="../bower_components/angular-route/angular-route.min.js"></script>
    <script src="../js/valscript.js"></script>

    <script src ="../js/jquery-3.1.1.js"></script>
    <script src="../js/bootstrap.min.js"></script>
    <script src="../bower_components/jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="../js/main.js"></script>
    
    <style>
body {
  position: relative;
  margin: 0;
  padding-bottom: 6rem;
  min-height: 100%;
  background-color: #f6f6f6;
}
form {
  background-color: #FFFFFF;
}
</style>

    </head>



    <body ng-app="validationApp" ng-controller="mainController">

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img alt ="logo" width ="30px" height ="30px" src ="../img/logo.png"></a>
          <a class ="navbar-brand" href ="../">junkTrade</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
      
            <!--this is not rendering the login page as it shoul -->
            <ul class = "nav navbar-nav navbar-right ">
                <li><a href ="login.php">Login</a></li>
            </ul>
            <ul class = "nav navbar-nav navbar-right ">
                <li><a href ="registration.phtml">Sign up</a></li>
            </ul>
           <!--<ul class="nav navbar-nav navbar-right ">
                <li><button type="button" class="btn btn-primary btn-lg" onclick="window.location='templates/login.html'">login</button></li>
            </ul> -->
         
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
<div class ="container">
  <h2 style="text-align: center; font-family: 'Acme', sans-serif; color:orange">Join JunkTrade</h2>
    <div class ="row">
      <div class="col-md-8 col-md-offset-2">
      
<form name="userForm" class="form-horizontal" method = "POST" action = "index.php/register" onsubmit="return register();" ng-submit="submitForm(userForm.$valid)" novalidate>
<fieldset>

<!-- Form Name -->
<legend style="text-align: center">Join JunkTrade</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="username">Username <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="username" name="username" type="text" placeholder="johnDoe123" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.username" ng-minlength="3" ng-maxlength="8" required="">
  <p ng-show="userForm.username.$error.minlength" class="help-block">Username is too short.</p>
  <p ng-show="userForm.username.$error.maxlength" class="help-block">Username is too long.</p>
  
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="firstname">First Name <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="firstname" name="firstname" type="text" placeholder="John" class="form-control input-md" ng-model="user.fname" type="text" placeholder="" class="form-control input-md" required="">
  
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="lastname">Last Name <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="lastname" name="lastname" type="text" placeholder="Doe" class="form-control input-md" ng-model="user.lname" type="text" placeholder="" class="form-control input-md" required="">
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="email">Email <span style="color:red">*</span> </label>  
  <div class="col-md-4">
  <input id="email" name="email" placeholder="johndoe@email.com" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.email" type="email" placeholder="johnDoe@example.com" class="form-control input-md" required="">
  <p ng-show="userForm.email.$error.email" class="help-block" >Invalid Email Address</p>    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="contact">Contact <span style="color:red">*</span> </label>  
  <div class="col-md-4">
  <input id="contact" name="contact" type="number" placeholder="8681234567" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.contact" type="text" placeholder="" class="form-control input-md" ng-minlength="10" ng-maxlength="10" required="">
  <p ng-show="userForm.contact.$error.minlength" class="help-block">Must be 10 digits((areacode)-contact#).</p>
  <p ng-show="userForm.contact.$error.maxlength" class="help-block">Must be 10 digits((areacode)-contact#).</p>
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="address">Address <span style="color:red">*</span></label>  
  <div class="col-md-4">
  <input id="address" name="address" type="text" placeholder="San Jaun" class="form-control input-md" ng-model="user.address" required="">
    
  </div>
</div>


<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="password">Password <span style="color:red">*</span> </label>
  <div class="col-md-4">
    <input id="password" name="password" type="password" placeholder="" class="form-control input-md" data-ng-model="user.password" ng-minlength="8" ng-maxlength="25" required="">
    <p ng-show="userForm.password.$error.minlength" class="help-block">Password is too short.</p>
  <p ng-show="userForm.password.$error.maxlength" class="help-block">Password is too long.</p>
  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="retypedpassword">Re-enter Password <span style="color:red">*</span> </label>
  <div class="col-md-4">
    <input id="retypedpassword" name="retypedpassword" type="password" placeholder="" class="form-control input-md" ng-model-options="{ updateOn: 'blur' }" ng-model="user.retypedpassword" required data-password-verify="user.password" required="">
  <p ng-show="userForm.retypedpassword.$error.passwordVerify" class="help-block">Passwords do not match </p>
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Submit"></label>
  <div class="col-md-4">
    <button id="saveBnt" name="saveBnt" class="btn btn-primary btn-block" type ="submit" ng-disabled="userForm.$invalid">Sign up for FREE</button>
  </div>
</div>

</fieldset>
</form>
  </div>
    </div>
</div>
<!--footer -->
  <div class="footer">
    <p> &copy; JunkTrade 2016 </p>
  </div>
<body>
</html>
